---
title: "CART"
output: html_document
---

```{r setup, include=FALSE}

setwd("E:/Files/Great Learning/All Courses/3-Data Mining/Project")

```


```{r}
therabankdata = read.csv("Thera_Bank.csv", sep="," ,header=TRUE) 
na.omit(therabankdata)
table(therabankdata$Personal.Loan)
prop.table(table(therabankdata$Personal.Loan))
round(prop.table(table(therabankdata$Personal.Loan)),2)

```
```{r}
set.seed(123)
library(caTools)
split = sample.split(therabankdata$Personal.Loan,SplitRatio = 0.7)
train = subset(therabankdata,split == TRUE)
test = subset(therabankdata,split == FALSE)
# check if
prop.table(table(train$Personal.Loan))
prop.table(table(test$Personal.Loan))

```
```{r}
# Change few variables to factor wherever you need whole number
head(train)
train$Education = as.factor(train$Education)
train$ZIP.Code = as.factor(train$ZIP.Code)
train$Family.members = as.factor(train$Family.members)
train$Personal.Loan = as.factor(train$Personal.Loan)
train$Securities.Account = as.factor(train$Securities.Account)
train$CD.Account = as.factor(train$CD.Account)
train$Online = as.factor(train$Online)
train$CreditCard = as.factor(train$CreditCard)
train$Education = as.factor(train$Education)
```
```{r}
#removing the first column of train
trainDS = train[,-1]
#gives first n rows of trainDS
head(trainDS)
#gives number of rows of trainDS
nrow(trainDS)
#gives a count of the different entries in the Personal Loan column in trainDS
table(trainDS$Personal.Loan)
#gives the fraction of "1" entries in the Personal Loan in trainDS
sum(trainDS$Personal.Loan=="1")/nrow(trainDS)
```
```{r}
#loads the library rpart into the system
library(rpart)
#loads the library rpart.plot into the system
library(rpart.plot)

#here we have built a formula where the variable Personal Loan is dependent on all the variables of trainDS
tree = rpart(formula = Personal.Loan ~ ., 
#building a decision tree
              data = trainDS, method = "class", cp=0, minbucket=3, model=TRUE)
#printing the decision tree in the console
tree

```
```{r}
#plotting the tree 
rpart.plot(tree)
```
```{r}
printcp(tree)
plotcp(tree)
```
```{r}
ptree = prune(tree, cp= 0.009 ,"CP")
printcp(ptree)
ptree

```
```{r}
rpart.plot(ptree)
```
```{r}
#gives the path by which we are going to arrive at that particular node
path.rpart(ptree,c(8,9,10,11,12,13,14,15))

```
```{r}
#as per our model, we are finding  the prediction of our Personal Loan variable
trainDS$prediction = predict(ptree, data=trianDS, type="class")
trainDS$prob1 = predict(ptree, trainDS, type="prob")[,"1"]
View(trainDS)

```


```{r}
#using the same functions for the test subset
head(test)
test$ZIP.Code = as.factor(test$ZIP.Code)
test$Family.members = as.factor(test$Family.members)
test$Personal.Loan = as.factor(test$Personal.Loan)
test$Securities.Account = as.factor(test$Securities.Account)
test$CD.Account = as.factor(test$CD.Account)
test$Online = as.factor(test$Online)
test$CreditCard = as.factor(test$CreditCard)

```
```{r}

testDS = test[,-1]
head(testDS)
nrow(testDS)
table(testDS$Personal.Loan)
sum(testDS$Personal.Loan=="1")/nrow(testDS)
```
```{r}

library(rpart)
library(rpart.plot)
tree2 = rpart(formula = Personal.Loan ~ .,  data = testDS, method = "class", cp=0, minbucket=3, model=TRUE) 
tree2

```
```{r}

rpart.plot(tree2)
```
```{r}
printcp(tree2)
plotcp(tree2)
```
```{r}
ptree2 = prune(tree2, cp=0.035  ,"CP")
printcp(ptree2)
ptree2


```
```{r}
rpart.plot(ptree2)
```
```{r}

path.rpart(ptree2,c(4,5,6,7))

```
```{r}
testDS$prediction2 = predict(ptree2, data=testDS, type="class")
testDS$probab1 = predict(ptree2, testDS, type="prob")[,"1"]
View(testDS)

```


```{r}
tbl=table(trainDS$Personal.Loan, trainDS$prediction)
print(tbl)

print((tbl[1,2]+tbl[2,1])/3500)
```
```{r}
tbl2=table(testDS$Personal.Loan, testDS$prediction2)
print(tbl2)

print((tbl[1,2]+tbl[2,1])/1500)

```
```{r}
library(ROCR)
library(ineq)

trainDS$prob1 = as.numeric(trainDS$prob1)
trainDS$Personal.Loan = as.numeric(trainDS$Personal.Loan)

predObj = prediction(trainDS$prob1,trainDS$Personal.Loan)
perf = performance(predObj, "tpr", "fpr")
plot(perf)

KS = max(perf@y.values[[1]]-perf@x.values[[1]])
print(KS)
auc = performance(predObj,"auc"); 
auc = as.numeric(auc@y.values)
print(auc)

gini = ineq(trainDS$prob1, type="Gini")
print(gini)
```


```{r}
testDS$probab1 = as.numeric(testDS$probab1)
testDS$Personal.Loan = as.numeric(testDS$Personal.Loan)

predObj2 = prediction(testDS$probab1,testDS$Personal.Loan)
perf2 = performance(predObj2, "tpr", "fpr")
plot(perf2)






```


```{r}
KS2 = max(perf@y.values[[1]]-perf@x.values[[1]])
print(KS2)

auc2 = performance(predObj2,"auc"); 
auc2 = as.numeric(auc2@y.values)
print(auc2)

```

```{r}
gini2 = ineq(testDS$probab1, type="Gini")
print(gini2)
```


```{r}




```


```{r}



```


```{r}

```
