---
title: "Project - 3"
author: "Yashaswi"
date: "October 7, 2019"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}

setwd("E:/Files/Great Learning/All Courses/3-Data Mining/Project")

```



```{r}
#Finding the number of rows and viewing the dataset
therabankdata = read.csv("Thera_Bank.csv", sep="," ,header=TRUE) 
newdata = therabankdata[,-1]
nrow(newdata)
head(newdata)


```
```{r}
#Converting to data frame and finding summary
str(newdata)
names(newdata)
summary(newdata)

```



```{r}
hist(newdata$Age..in.years.,col="Red",main = "Histogram of Age ",xlab="Age(in years)")
```
```{r}
hist(newdata$Experience..in.years.,col="Red",main = "Histogram of Experience ",xlab="Experience(in years)")
```
```{r}
hist(newdata$Income..in.K.month.,col="Red",main = "Histogram of Income ",xlab="Income(in K )")
```
```{r}
hist(newdata$ZIP.Code,col="Red",main = "Histogram of Zip Code",xlab="Zip Code")
```
```{r}
hist(newdata$Family.members,col="Red",main = "Histogram of Family Members",xlab="Family Members")
```
```{r}
hist(newdata$CCAvg,col="Red",main = "Histogram of Credit Card Average",xlab="Credit Card Average ")
```
```{r}
hist(newdata$Education,col="Red",main = "Histogram of Education",xlab="Education ")
```
```{r}
hist(newdata$Mortgage,col="Red",main = "Histogram of Mortgage",xlab="Mortgage")
```
```{r}
hist(newdata$Personal.Loan,col="Red",main = "Histogram of Personal Loan",xlab="Personal Loan")
```
```{r}
hist(newdata$Securities.Account,col="Red",main = "Histogram of Securities Account",xlab="Securities Account")
```
```{r}
hist(newdata$CD.Account,col="Red",main = "Histogram of Certificate of Deposit Account",xlab="CD Account")
```
```{r}
hist(newdata$Online,col="Red",main = "Histogram of Online",xlab="Online")
```
```{r}
hist(newdata$CreditCard,col="Red",main = "Histogram of Credit Card",xlab="Credit Card")
```
```{r}
plot(newdata$Age..in.years.,newdata$Personal.Loan, main = "Scatterplot of Age and Personal Loan",xlab="Age",ylab="Personal Loan",pch=19, col=c("red","blue"))

```
```{r}
plot(newdata$Experience..in.years.,newdata$Education, main = "Scatterplot of Exeperience and Education",xlab="Experience",ylab="Education",pch=19, col=c("red","blue"))

```
```{r}
plot(newdata$Income..in.K.month.,newdata$Securities.Account, main = "Scatterplot of Income and Securities Account",xlab="Income",ylab="Securities Account",pch=19, col=c("red","blue"))

```
```{r}
plot(newdata$ZIP.Code,newdata$Online, main = "Scatterplot of Zip Code and Online",xlab="Zip Code",ylab="Online",pch=19, col=c("red","blue"))
```
```{r}
plot(newdata$Family.members,newdata$Mortgage, main = "Scatterplot of Family Members and Mortgage",xlab="Family Members",ylab="Mortagage",pch=19, col=c("red","blue"))
```
```{r}
plot(newdata$Education,newdata$CD.Account, main = "Scatterplot of Education and CD Account",xlab="Education",ylab="CD Account",pch=19, col=c("red","blue"))
```
```{r}
plot(newdata$CCAvg,newdata$CreditCard, main = "Scatterplot of Credit Card Average and Credit Card",xlab="CC Avg",ylab="Credit Card",pch=19, col=c("red","blue"))
```
```{r}
plot(newdata$Age..in.years.,newdata$Income..in.K.month., main = "Scatterplot of Age and Income",xlab="Age",ylab="Income",pch=19, col=c("red","blue"))
```
```{r}
plot(newdata$ZIP.Code,newdata$Family.members, main = "Scatterplot of Zip Code and Family Members",xlab="Zip Code",ylab="Family Members",pch=19, col=c("red","blue"))
```
```{r}
plot(newdata$Experience..in.years.,newdata$Personal.Loan, main = "Scatterplot of Experience and Personal loan",xlab="Experience",ylab="Personal Loan",pch=19, col=c("red","blue"))
```
```{r}
table(therabankdata$Personal.Loan)
prop.table(table(therabankdata$Personal.Loan))
round(prop.table(table(therabankdata$Personal.Loan)),2)

```
```{r}
set.seed(123)
library(caTools)
split = sample.split(therabankdata$Personal.Loan,SplitRatio = 0.7)
train = subset(therabankdata,split == TRUE)
test = subset(therabankdata,split == FALSE)
# check if
prop.table(table(train$Personal.Loan))
prop.table(table(test$Personal.Loan))

```
```{r}
str(train)
names(train)
train$ID = as.numeric(train$ID)
train$Income..in.K.month. = as.numeric(train$Income..in.K.month.)
train$Age..in.years. = as.numeric(train$Age..in.years.)
train$Experience..in.years. = as.numeric(train$Experience..in.years.)
train$ZIP.Code = as.numeric(train$ZIP.Code)
train$Family.members = as.numeric(train$Family.members)
train$Education = as.numeric(train$Education)
train$Personal.Loan = as.numeric(train$Personal.Loan)
train$Securities.Account = as.numeric(train$Securities.Account)
train$CD.Account = as.numeric(train$CD.Account)
train$Online = as.numeric(train$Online)
train$CreditCard = as.numeric(train$CreditCard)
train$Mortgage = as.numeric(train$Mortgage)
train$CCAvg = as.numeric(train$CCAvg)
head(train)

```
```{r}
distMatrix = dist(x=train[,-1], method = "euclidean") 
print(distMatrix,digits = 3)
```
```{r}
## scale function standardizes the values
train.Scaled = scale(train[,-1])
print(train.Scaled)

```
```{r}
apply(train.Scaled,2,mean)
apply(train.Scaled,2,sd)

```
```{r}
# Computing distance matrix again with scaled data
distMatrix.Scaled = dist(x=train.Scaled, method = "euclidean") 
print(distMatrix.Scaled, digits = 3)

```
```{r}
cluster = hclust(distMatrix.Scaled, method = "average")
plot(cluster)
```
```{r}
clust.height=cluster$height
print(clust.height)
```
```{r}
clust.height = sort(clust.height, decreasing = TRUE)
plot(clust.height)
lines(clust.height,lty = 2, lwd=2)

```
```{r}
# Plot rectagles defining the clusters for K of 100
plot(cluster)
rect.hclust(cluster, k=100, border="red")

```



```{r}

train$Cluster = cutree(cluster, k=100)
print(train)
```
```{r}
## Aggregating columns 2:14 for each cluster by their means
trainProfile = aggregate(train[,-c(1,15)],list(train$Cluster),FUN="mean")
print(trainProfile)

```
```{r}
str(test)
names(test)
test$ID = as.numeric(test$ID)
test$Income..in.K.month. = as.numeric(test$Income..in.K.month.)
test$Age..in.years. = as.numeric(test$Age..in.years.)
test$Experience..in.years. = as.numeric(test$Experience..in.years.)
test$ZIP.Code = as.numeric(test$ZIP.Code)
test$Family.members = as.numeric(test$Family.members)
test$Education = as.numeric(test$Education)
test$Personal.Loan = as.numeric(test$Personal.Loan)
test$Securities.Account = as.numeric(test$Securities.Account)
test$CD.Account = as.numeric(test$CD.Account)
test$Online = as.numeric(test$Online)
test$CreditCard = as.numeric(test$CreditCard)
test$Mortgage = as.numeric(test$Mortgage)
test$CCAvg = as.numeric(test$CCAvg)
head(test)

```
```{r}
distMatrix2 = dist(x=test[,-1], method = "euclidean") 
print(distMatrix2,digits = 3)

```
```{r}
test.Scaled = scale(test[,-1])
print(test.Scaled)
```
```{r}
apply(test.Scaled,2,mean)
apply(test.Scaled,2,sd)
```
```{r}

distMatrix2.Scaled = dist(x=test.Scaled, method = "euclidean") 
print(distMatrix2.Scaled, digits = 3)

```
```{r}
cluster2 = hclust(distMatrix2.Scaled, method = "average")
plot(cluster2)
```
```{r}
cluster2$height
```
```{r}

plot(cluster2)
rect.hclust(cluster2, k=100, border="red")

```
```{r}
test$Cluster = cutree(cluster2, k=100)
print(test)
```
```{r}
testProfile = aggregate(test[,-c(1,15)],list(test$Cluster),FUN="mean")
print(testProfile)

```
```{r}

```






